### ISSUE TITLE
Possibility of uploading workstream meeting recordings to CDF Youtube Channel

### ISSUE THREAD

**Issue by fdegir** [cdfoundation/foundation#202]
SIG Interoperability has workstreams for people interested in specific topics in the area of interoperability to come together and start working on those in a collaborative manner to make sure the topic gets the attention it needs while keeping the SIG updated with regards to their progress, needs, and so on.

The workstreams may record their meetings and there may be times that it would be valuable to make those recording available for the rest of the SIG and the community.

The question we have is; would it be possible and make sense to get those recordings uploaded to  CDF Youtube channel?

The minutes where this was discussed is available below.

https://hackmd.io/HuufSDMaTPyb3qxkyBKg3A

/cc @agrimmer @e-backmark-ericsson @ravilach @rakhbari @MarckK

**Comment by jsalinas29** [comment]
@fdegir - few questions: 
- are folks using the cdf zoom account to record their mtgs? 
- if they are not, can we get them to switch and I can help get that set up too
- i believe there is a way to automate zoom recordings into youtube (need to look into this)
- or we can set up a google drive and the meeting recordings can be dropped in there I can upload to youtube 

please lmk

**Comment by rakhbari** [comment]
@jsalinas29 Hi Jacque. I didn't realize there's a CDF zoom account. I ended up using my company's (eBay) zoom account to provide the meeting room and do the recording.

But because eBay's zoom CNAME is under eBay Corp login + 2FA, I subsequently had to download the raw MP4 file of the recording, upload it to my personal YouTube account and that was the only way to give others access to view it. But I'd much prefer to have that recording under a CDF account somewhere.

Yes, if you can set us up with a CDF zoom account, that would solve it. In the meantime, is there any publicly accessible storage site CDF has where I can upload last week's recording MP4 file?

**Comment by jsalinas29** [comment]
@rakhbari - can you add me to the working group calendar invite? I will create a recurring meeting in the CDF zoom account for this group and set it up to automatically start recording. 

You can add the file here: https://drive.google.com/drive/folders/16FSOuPTzBhlz8owMaB5I_6d-MT83rVyo?usp=sharing

**Comment by rakhbari** [comment]
@jsalinas29 Management of WG calendar, etc, is up to Fatih @fdegir .

**Comment by jsalinas29** [comment]
​Sure, just need to know the date, time, etc to set up the meeting on zoom.
Thanks! ​  





On Wed, Jun 17, 2020 10:59 PM, rakhbari notifications@github.com  wrote:


@jsalinas29  Management of WG calendar, etc, is up to Fatih @fdegir  .

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.



Jacqueline SalinasContinuous Delivery FoundationDirector of Ecosystem & Co
mmunityjsalinas@contractor.linuxfoundation.orghttps://calendly.com/jsalinas-cdf
408 218 0667

**Comment by fdegir** [comment]
I believe @e-backmark-ericsson manages the workstream calendar.

**Comment by e-backmark-ericsson** [comment]
@jsalinas29 , the 'Events in CI/CD' workstream meet every second Monday, at 6.30-7.30 pm CET. Next meeting is this coming Monday - https://time.is/compare/1830_22_June_2020_in_CET/EST/EDT/PT

Here are our meeting notes: https://hackmd.io/QijjoIAiSeCNhaLpXhr05w?view

I don’t have access to update the CDF calendar with an entry for this workstream. Would it be possible to add an entry about this workstream to that calendar? @fdegir/@jsalinas29, could anyone of you add that entry?

**Comment by jsalinas29** [comment]
@rakhbari, @fdegir & @e-backmark-ericsson - this is your recurring meeting for this SIG. I've set it up so it automatically starts to record & saves it to the cloud instead of locally. Next step for me is to figure out how to automate the recording from zomm to youtube. Let me know if you need any help on Monday. Ping me on slack , if you have any issues using this zoom. I don't own the meeting so I am unable to update the zoom info. Thanks! 

Hi there, 

You are invited to a Zoom meeting. 
When: Jun 22, 2020 06:30 PM Madrid 

Register in advance for this meeting:
https://zoom.us/meeting/register/tJMrcemvrzksGtSgbE3-44y5nBvCkKI6X2MT 

After registering, you will receive a confirmation email containing information about joining the meeting.

**Comment by e-backmark-ericsson** [comment]
Thanks for setting this up @jsalinas29! We'll try to use this bridge on Monday.

**Comment by rakhbari** [comment]
@jsalinas29 Thanks Jacque for that Google drive link. I've created an `Events in CD` folder under `CDF Interoperability SIG` folder where I've uploaded the recording for our WG meeting of 2020-06-08:

https://drive.google.com/drive/folders/1D_H_ujsh921WI13fTPGj1vBBGwS9iviC

Feel free to move this recording to any other appropriate place.

**Comment by markyjackson-taulia** [comment]
I have had sync with @jsalinas29 and will take over this issue

**Comment by markyjackson-taulia** [comment]
This issue has been addressed. I will document what the details are and how to manage them. I will pr that doc into the repo by end of the week.
Can someone assign this issue to me?

**Comment by tracymiranda** [comment]
@markyjackson-taulia can I close this issue or is there still some outstanding stuff to address?

**Comment by markyjackson-taulia** [comment]
Yes this has been handled￼

**Comment by tracymiranda** [comment]
Thank you!
