### ISSUE TITLE
Add Nikema Prophet to the Spinnaker TweetDeck

### ISSUE THREAD

**Issue by dnilasor** [cdfoundation/foundation#217]
@jsalinas29 or @tracymiranda can you please help me get @prophen, Nikema Prophet, added to the Spinnaker Tweetdeck? She'll be posting on behalf of Spinnaker to promote the Summit and other community initiatives. Thanks!

**Comment by jsalinas29** [comment]
Yes, I am working with Nikema to get her added. Thanks!  





On Mon, Oct 5, 2020 10:01 PM, Rosalind Benoit notifications@github.com  wrote:


@jsalinas29  or @tracymiranda  can you please help me get @prophen, Nikema
Prophet, added to the Spinnaker Tweetdeck? She'll be posting on behalf of
Spinnaker to promote the Summit and other community initiatives. Thanks!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.



Jacqueline SalinasContinuous Delivery FoundationDirector of Ecosystem &
Communityjsalinas@cd.foundationhttps://calendly.com/jsalinas-cdf
408 218 0667
