### ISSUE TITLE
Update CB board rep Anders W

### ISSUE THREAD

**Issue by tracymiranda** [cdfoundation/foundation#221]
- [x]  Added to board meeting calendar invite
- [x]  Added to CDF Board calendar
- [x]  Added to CDF Board Google Drive
- [x]  Added to CDF cdf-gb mailing list
- [ ]  Added to Governing Board page on website

**Comment by galemccommons** [comment]
@tracymiranda @jsalinas29 do either of you have Anders headshot/bio? If no, I can reach out directly. Thanks! -G

**Comment by jsalinas29** [comment]
I do not have his headshot or bio. Can you share with me after you reach out
to them? I need it to update our decks too! Thanks.  





On Wed, Nov 11, 2020 5:10 PM, galemccommons notifications@github.com  wrote:


@tracymiranda  @jsalinas29  do either of you have Anders headshot/bio? If no, I
can reach out directly. Thanks! -G

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.



Jacqueline SalinasContinuous Delivery FoundationDirector of Ecosystem &
Communityjsalinas@cd.foundationhttps://calendly.com/jsalinas-cdf
408 218 0667

**Comment by tracymiranda** [comment]
We have received headshots/bio forwarded to @galemccommons @jsalinas29

**Comment by galemccommons** [comment]
Website updated with headshot and bio
