### ISSUE TITLE
[Nominations Open] Most Valuable Jenkins Contributor 🏆

### ISSUE THREAD

**Issue by zestyroxy** [cdfoundation/foundation#318]
This issue is to receive nominations for the Most Valuable Jenkins Contributor 2021. This award is presented to an individual who has contributed to the Jenkins project the most through new features, bug fixes or plugin development efforts.

To nominate someone, reply to this issue with the following:

1. Full name of the person you’re nominating
2. Short description of their contributions to the Continuous Delivery Foundation and why they should win.

Nomination deadline: Friday, April 30, 2021
**EXTENDED to Friday, May 14, 2021**

More details are available here: https://cd.foundation/cdf-community-awards/

**Comment by Wadeck** [comment]
Tim Jacomb

@timja participated in lots of different areas, always present, close to the OSS topics, involved both in development and in infra, they guys we are seeing everywhere. In addition, he took the Release officer role since the last election from December 2020.
From my PoV his main contribution was about the table-to-div migration effort. He put lots of efforts to ensure the code base is not (too) broken, before, during and after the migration.
He already received the 2020 award, but his efforts did not stop!

Thanks a lot for what you are doing.

**Comment by danpopSD** [comment]
I would like to nominate Steven Terrana. 

Steven is best known for his work as the lead maintainer of the Jenkins Templating Engine (JTE), which provides teams a framework to develop tool-agnostic Jenkins pipelines that can be shared across teams. On JTE, Steven has contributed to the Jenkins pipeline documentation as well as many popular Jenkins plugins such as Pipeline: Groovy, the Groovy CPS library, Declarative Pipeline Syntax, the Git plugin, and Jenkinsfile Runner. 

As well as maintaining JTE, Steven works hard to evangelize Jenkins and contribute to the community at large through his efforts on the Jenkins Pipeline Authoring SIG and his role as a CDF Ambassador. He's published multiple blog posts on jenkins.io, the CDF blog and newsletter, the Jenkins Online Meetup, and spoken about JTE/Jenkins at industry-leading events such as DevOps World, Kubecon, Red Hat Summit.

Steven is one of the best Jenkins  SME's  i have ever had the pleasure of working with and an even better human being in our community.

**Comment by oleg-nenashev** [comment]
I would like to nominate Dr. Ullrich Hafner (@uhafner on GitHub). Ullrich is a long-term Jenkins contributor, he has joined the project more than 10 years ago. There are so many contributions by him in the project. Just to list a few recent ones:

* [Warnings NG Plugin](https://plugins.jenkins.io/warnings-ng/) - the most widely used static analysis reporting plugins in Jenkins, with 20k+ installations.
* Mentoring the [GitHub Checks API for Jenkins Plugins](https://www.jenkins.io/projects/gsoc/2020/projects/github-checks/) project during GSoC 2020, together with @timja. The [plugin](https://plugins.jenkins.io/github-checks/) created by @XiongKezhi provided the long anticipated integration between Jenkins and GitHub. Thanks to this project we also improved reporting from ci.jenkins.io, and it improved contributor experience in the community.
* Introducing students from University of Applied Sciences Munich to the open source developer tools and to the Jenkins project. Many of them contributed to the project, including test automation, refactoring, and various features.
* Participating in the Jenkins UX SIG and providing feedback on the Jenkins UI/UX revamp initiatives.
* Creating and maintaining API plugins for modern JavaScript-based UI, e.g. [these plugins](https://www.jenkins.io/blog/2020/03/17/ui-plugins/#new-user-interface-plugins).
* [Autograding Plugin](https://github.com/jenkinsci/autograding-plugin) which provides quality metrics and analytics for projects within Jenkins.
* Participating in Jenkins outreach programs and sharing experiences, e.g. [Hands On: Beautify the user interface of Jenkins reporter plugins](https://www.jenkins.io/blog/2020/03/17/ui-plugins/) during the 2020 UI/UX contributor summit.
* Contributions to the [Jenkins Acceptance Test Harness](https://github.com/jenkinsci/acceptance-test-harness) suite. It is instrumental to Jenkins WebUI and compatibility testing.

And this is not a full list! Thanks @uhafner!

**Comment by MarckK** [comment]
I would like to nominate [Vibhav Bobade](https://github.com/waveywaves) (@waveywaves). Vibhav has initiated and is currently leading two work streams to create a cloud native Jenkins, while also facilitating greater interoperability between Jenkins and other CI/CD tools and platforms. He is an active contributor in the [Jenkins Cloud Native SIG](https://github.com/jenkinsci/sig-cloud-native) and has proposed 2 GSoC 2021 project ideas and volunteered to be the lead mentor on both.

In Vibhav’s own words, his vision for this work is to enable Jenkins to be a Cloud Native CI/CD platform:

'Jenkins is known for its modularity. The fact that the original design made it possible to extend Jenkins with plugins made the tool future-proof, to some extent. With extensions such as the Docker plugin, Jenkins had already started its journey to the cloud and with the creation and success of the Kubernetes plugin it was clear that Jenkins is not just accommodating to the cloud but helping existing users to be part of the journey as well. 

But, the solutions provided by these plugins aren’t completely cloud native since they were created to have Jenkins jobs run on Kubernetes and not make Jenkins a cloud native CI/CD platform. For that to happen, Jenkins needs to leverage tools that are already resident in the cloud and delegate to these tools, acting as a central platform to curate and manage CI/CD pipelines.'
-- Vibhav Bobade, [Paving the way for Jenkins interoperability in the Cloud ](https://cd.foundation/blog/2021/04/21/paving-the-way-for-jenkins-interoperability-in-the-cloud/)

**First Jenkins initiative Vibhav is leading:**
 
Vibhav initiated / founded the [Tekton Client Plugin for Jenkins](https://github.com/jenkinsci/tekton-client-plugin) to enable [Tekton](https://tekton.dev/) as the build engine to carry out all the Jenkins Kubernetes builds. Vibhav first showcased the plugin at [cdCon 2020](https://www.youtube.com/watch?v=17T3-9LeXGA) and has proposed a [GSoC 2021 project idea to extend the plugin to provide a DSL for Tekton](https://www.jenkins.io/projects/gsoc/2021/project-ideas/tekton-client-plugin/). 
 
**Second Jenkins initiative Vibhav is leading:**
 
Microservices are the de facto architecture of the cloud and events are the primary way in which microservices communicate a change of state. [CloudEvents is a specification](https://github.com/cloudevents/spec) for describing event data in common, standardised formats. This provides interoperability across services, platforms, and systems. CI/CD tools, such as Tekton, have started to support CloudEvents and the CDF Event SIG is looking at how events (based on CloudEvents) can help to create CI/CD systems with a decoupled architecture that is scalable and resilient to failures.
 
Vibhav has proposed a [GSOC 2021 project idea for Jenkins to allow emitting events and triggering jobs on certain events](https://www.jenkins.io/projects/gsoc/2021/project-ideas/cloudevents-plugin/), bringing Jenkins one step closer interoperability with other technologies in the cloud. 
 

**Additional Contributions and Involvement in the Jenkins project:**
 
Vibhav joined the community as a [Jenkins Kubernetes Operator](https://github.com/jenkinsci/kubernetes-operator) contributor. As a part of his work at Red Hat, he proposed a number of patches to the Kubernetes Operator, and then became one of lead developers of the [Jenkins Automation Operator](https://github.com/jenkinsci/jenkins-automation-operator)  created by Red Hat. Vibhav was a contributor in the Jenkins Kubernetes Operator open governance proposal. At Red Hat Vibhav also contributes to the OpenShift integration plugins.
 
Vibhav also created the [Jenkinsfile Runner Operator prototype](https://github.com/waveywaves/jenkinsfile-runner-operator).

**Comment by zestyroxy** [comment]
We are no longer accepting nominations. Thank you to everyone who nominated someone and good luck to the nominees!
