### ISSUE TITLE
[Nominations Open] Jenkins Security MVP 🏆

### ISSUE THREAD

**Issue by zestyroxy** [cdfoundation/foundation#319]
This issue is to receive nominations for the Jenkins Security MVP 2021. This award is presented to an individual most consistently providing excellent security reports or resolving security issues.

To nominate someone, reply to this issue with the following:

1. Full name of the person you’re nominating
2. Short description of their contributions to the Continuous Delivery Foundation and why they should win.

Nomination deadline: Friday, April 30, 2021
**EXTENDED to Friday, May 14, 2021**

More details are available here: https://cd.foundation/cdf-community-awards/

**Comment by daniel-beck** [comment]
**Wadeck Follonier**

@Wadeck is a regular and prolific contributor to the Jenkins project and a key member of the Jenkins security team.

<details>
<summary>Since early 2020, the Jenkins project has credited him for reporting vulnerabilities resulting in 69 CVEs across Jenkins and Jenkins plugins.</summary>

CVE-2020-2095
CVE-2020-2103
CVE-2020-2111
CVE-2020-2114
CVE-2020-2136
CVE-2020-2137
CVE-2020-2140
CVE-2020-2141
CVE-2020-2142
CVE-2020-2147
CVE-2020-2148
CVE-2020-2152
CVE-2020-2161
CVE-2020-2169
CVE-2020-2174
CVE-2020-2176
CVE-2020-2188
CVE-2020-2190
CVE-2020-2193
CVE-2020-2194
CVE-2020-2196
CVE-2020-2199
CVE-2020-2201
CVE-2020-2205
CVE-2020-2206
CVE-2020-2207
CVE-2020-2217
CVE-2020-2220
CVE-2020-2221
CVE-2020-2222
CVE-2020-2224
CVE-2020-2225
CVE-2020-2226
CVE-2020-2227
CVE-2020-2229
CVE-2020-2231
CVE-2020-2236
CVE-2020-2237
CVE-2020-2238
CVE-2020-2243
CVE-2020-2244
CVE-2020-2257
CVE-2020-2259
CVE-2020-2262
CVE-2020-2263
CVE-2020-2264
CVE-2020-2265
CVE-2020-2266
CVE-2020-2267
CVE-2020-2268
CVE-2020-2269
CVE-2020-2270
CVE-2020-2271
CVE-2020-2272
CVE-2020-2273
CVE-2020-2274
CVE-2020-2279
CVE-2020-2287
CVE-2020-2289
CVE-2020-2290
CVE-2020-2292
CVE-2020-2310
CVE-2020-2316
CVE-2020-2317
CVE-2021-21603
CVE-2021-21605
CVE-2021-21606
CVE-2021-21607
CVE-2021-21611
</details>

<details>
<summary>He's authored about a dozen security fixes that were part of several Jenkins security updates in 2020 and 2021.</summary>

* [Jenkins 2.219 and LTS 2.204.2](https://jenkins.io/security/advisory/2020-01-29/)
* [Jenkins 2.228, LTS 2.204.6, and LTS 2.222.1](https://jenkins.io/security/advisory/2020-03-25/)
* [Jenkins 2.245 and LTS 2.235.2](https://jenkins.io/security/advisory/2020-07-15/)
* [Jenkins 2.252 and LTS 2.235.4](https://jenkins.io/security/advisory/2020-08-12/)
* [Jenkins 2.275 and LTS 2.263.2](https://jenkins.io/security/advisory/2021-01-13/)

SECURITY-1641
SECURITY-1659
SECURITY-1695
SECURITY-1697
SECURITY-1704
SECURITY-1781
SECURITY-1796
SECURITY-1868
SECURITY-1901
SECURITY-1902
SECURITY-1955
(Possibly others)
</details>

Under his direction, master students at Aix-Marseille University investigated the Jenkins plugin ecosystem in early 2021 as part of their coursework, learning to identify common classes of vulnerabilities and discovering several vulnerabilities in Jenkins plugins, the first of which have been fixed in [the 2021-03-30 security advisory](https://www.jenkins.io/security/advisory/2021-03-30/).

**Comment by daniel-beck** [comment]
**Nils Emmerich**

[Script Security Plugin](https://plugins.jenkins.io/script-security/) is an important piece of Jenkins security: It protects the scripting capabilities of Jenkins Pipeline and dozens of other plugins in the Jenkins plugin ecosystem, preventing low privilege authors of such scripts from executing arbitrary code. Script Security Plugin is installed on almost all Jenkins instances, and sandbox bypasses usually have a severe impact in common configurations.

Despite having been the subject of research from multiple security researchers in the past, Nils was able to find several security vulnerabilities in Script Security that allowed attackers to bypass the existing protection mechanisms, and reported them to the Jenkins project in late 2019 and early 2020:

* [SECURITY-1538 / CVE-2019-10393, CVE-2019-10394, CVE-2019-10399, CVE-2019-10400](https://www.jenkins.io/security/advisory/2019-09-12/#SECURITY-1538)
* [SECURITY-1579 / CVE-2019-10431](https://www.jenkins.io/security/advisory/2019-10-01/#SECURITY-1579)
* [SECURITY-1658 / CVE-2019-16538](https://www.jenkins.io/security/advisory/2019-11-21/#SECURITY-1658)
* [SECURITY-1710 / CVE-2020-2109](https://www.jenkins.io/security/advisory/2020-02-12/#SECURITY-1710)
* [SECURITY-1713 / CVE-2020-2110](https://www.jenkins.io/security/advisory/2020-02-12/#SECURITY-1713)
* [SECURITY-1754 / CVE-2020-2134, CVE-2020-2135](https://www.jenkins.io/security/advisory/2020-03-09/#SECURITY-1754)

**Comment by Wadeck** [comment]
**Daniel Beck**

Even if it sounds to be a return of favor, it is not. @daniel-beck is the security officer of the project since the beginning of that position. Without detailing the number of vulnerabilities he reported directly, his main contributions are somewhere else.
He wrote several scripts / tools to help the Jenkins CERT (= Security team), to ease their tasks, reduce burden, add safety net and drastically increase efficiency.
Also, he was the main contributor to the different [CodeQL rules](https://www.jenkins.io/blog/2020/11/04/codeql/) using his knowledge of the area. Due to that, the security team was able to improve its auditing capacities.
From my PoV, his main contribution for security is about his continuous efforts to track the vulnerabilities, from the reports, the triaging of the findings, the communication with the maintainers, the review of the fixes, the coordination of the release and the advisory publication. All this small tasks are done every day, and without him playing the role of the "oil" in this huge engine, the security of the project would not be the same.

Thanks for the efforts, the involvement and more generally, your love for this project!

**Comment by Wadeck** [comment]
**Kevin Gerroudj**

During his master project at [Aix-Marseille](https://formations.univ-amu.fr/ME5SIN-PRSIN5AA.html) about security auditing/pentesting, @KevGuer was the most prolific student, discovering several vulnerabilities, especially XSS ones, had a very deep interest in the area, the project, always trying to learn more and more. He even proposed some corrections in addition to the different reports he wrote.

The first advisory with some of his findings was recently published: https://www.jenkins.io/security/advisory/2021-03-30/.

Having more people involved like him in the project could be only beneficial!

**Comment by zestyroxy** [comment]
We are no longer accepting nominations. Thank you to everyone who nominated someone and good luck to the nominees!
