### ISSUE TITLE
[Nominations Open] Jenkins Security MVP 2022 🏆

### ISSUE THREAD

**Issue by zestyroxy** [cdfoundation/foundation#367]
This issue is to receive nominations for the Jenkins Security MVP 2022. This award is presented to an individual most consistently providing excellent security reports or resolving security issues.

To nominate someone, reply to this issue with the following:

1. Full name of the person you’re nominating
2. Short description of their contributions to the Continuous Delivery Foundation and why they should win.

**Nomination Deadline:** ~~Tuesday, March 29, 2022~~ [EXTENDED to April 11, 2022]

More details are available here: https://cd.foundation/cdf-community-awards/

**Comment by daniel-beck** [comment]
**Wadeck Follonier**

I already nominated @Wadeck last year (https://github.com/cdfoundation/foundation/issues/319#issuecomment-823813082) and since then he's only become more important to the project: Since December, he's [the Jenkins security officer](https://www.jenkins.io/blog/2021/12/03/election-results/), leading the [Jenkins security team](https://www.jenkins.io/security/team/) efforts in communicating with reporters and maintainers, coordinating releases and security advisories, investigating potential security issues and fixing them; as well as operating the [Jenkins CVE Numbers Authority](https://www.jenkins.io/security/cna/) to ensure everyone has accurate information about security issues in Jenkins.

**Comment by zestyroxy** [comment]
🚫 Nominations are now closed! 
Voting will start April 13, link will be posted here.

**Comment by zestyroxy** [comment]
Thank you, everyone! Award ceremony happened at cdCon 2022.
Congratulation to the winner @Wadeck! 
All winners here: https://github.com/cdfoundation/awards/blob/main/README.md
