### ISSUE TITLE
[Nominations Open] Most Valuable Jenkins Advocate 2022 🏆

### ISSUE THREAD

**Issue by zestyroxy** [cdfoundation/foundation#368]
This issue is to receive nominations for the Most Valuable Jenkins Advocate 2022. This award is presented to an individual who has helped advocate for Jenkins through organization of (a) local Jenkins Area Meet­up(s) or virtual equivalent.

To nominate someone, reply to this issue with the following:

1. Full name of the person you’re nominating
2. Short description of their contributions to the Continuous Delivery Foundation and why they should win.

**Nomination Deadline:** ~~Tuesday, March 29, 2022~~ [EXTENDED to April 11, 2022]

More details are available here: https://cd.foundation/cdf-community-awards/

**Comment by alyssat** [comment]
@jmMeessen and I  are pleased to nominate Kris Stern (@krisstern on GitHub) for the Most Valuable Advocate award. Kris is a new contributor to the Jenkins project, and has shown exemplary dedication to the meaning of  giving back.  Kris volunteered to be a mentor and an org admin for Jenkins Google Summer of Code 2022.  Since signing up he has displayed genuine commitment to the success of this program.  He is present at every office hours even when it is 1am his local time. He is always available and responsive to all GSoC potential contributors, providing feedback, guidance and technical advice. At times Kris could be seen gracefully challenging potential contributors to think outside of the box, as a good mentor does.  There are times throughout the program where the ratio of potential contributors outnumbered the mentors prompting a flurry of inquiries, Kris rose to the occasion and took the lead to address those inquiries, even when he is the very few doing so.

Kris’ contributions, commitment, and thoughtfulness amplify what the Jenkins community stands for which is fostering an open and welcoming community.

Many Thanks Kris!

**Comment by MarkEWaite** [comment]
Nomination: **Gavin Mogan** (@halkeye)

Gavin is a member of the [Jenkins Board](https://www.jenkins.io/project/board/).  

He is the primary maintainer of the [Jenkins plugins site](https://plugins.jenkins.io/).  He was the lead implementer of [plugin site enhancements](https://github.com/jenkins-infra/plugin-site/pulls?q=is%3Apr+author%3Ahalkeye) including documentation conversion from wiki to GitHub, site search implementation with Algolia search, and usability improvements for navigation and issue reporting.

He leads the development and evangelism of the [community.jenkins.io site](https://community.jenkins.io/).  He's encouraged public sharing of meeting recordings and meeting notes like the [UX SIG](https://community.jenkins.io/tag/sig-ux), [Advocacy and Outreach SIG](https://community.jenkins.io/tag/sig-advocacy-and-out), [Platform SIG](https://community.jenkins.io/tag/sig-platform), and [Governance](https://community.jenkins.io/tag/governance).  He's a key contributor to address user questions and help with issues reported on the community site.

He converted the Jenkins is the Way site from a [Wordpress site](https://jenkinsistheway.io/) to a GitHub repository hosted at [stories.jenkins.io](https://stories.jenkins.io) so that we can better collect success stories from Jenkins users.

He created the [preview facility](https://github.com/jenkins-infra/jenkins.io/pulls?q=is%3Apr+preview+author%3Ahalkeye+is%3Aclosed+preview) for jenkins.io pull requests so that contributors can see the web presentation of their pull requests before they are merged.

**Comment by zestyroxy** [comment]
🚫 Nominations are now closed! 
Voting will start April 13, link will be posted here.

**Comment by zestyroxy** [comment]
Thank you, everyone! Award ceremony happened at cdCon 2022. 
Congratulation to the winner @halkeye! 
All winners here: https://github.com/cdfoundation/awards/blob/main/README.md
