### ISSUE TITLE
[Nominations Open] Top Spinnaker Community Contributor Award 2022 🏆 

### ISSUE THREAD

**Issue by justjenu** [cdfoundation/foundation#369]
This issue is to receive nominations for the Spinnaker Most Valuable Contributor (MVC) Award 2022.

This award recognizes excellence of contributions to the Spinnaker project, which may be any or a combination of contributions, advocacy, community involvement, and fostering adoption in other communities.

To nominate someone, reply to this issue with the following:

Full name of the person you’re nominating
Short description of their contributions to the Spinnaker project and why they should win.
Nomination Deadline: Tuesday, March 29, 2022

More details are available here: https://cd.foundation/cdf-community-awards/

cc: @zestyroxy fyi - i created this for Spinnaker community

**Comment by benmappen** [comment]
+1 for Cameron!

**Comment by zestyroxy** [comment]
Thanks @justjenu, added to the CDF award page: https://cd.foundation/cdf-community-awards/

**Comment by benmappen** [comment]
I'd also like to nominate Jason McIntosh

Jason is one of the most active members of the Spinnaker community, especially in Spinnaker Slack, and spends countless hours helping answer technical questions from other community members. Many other active members of the community rely on Jason's expertise and often at-mention him directly because they know he likely has the answer. Without Jason's contribution, the number of successful Spinnaker users would certainly be far fewer. This impact alone is well worth him winning the award.

**Comment by zestyroxy** [comment]
Thank you everyone! Award ceremony happened at cdCon 2022. Congratulation to the winner. All winners here: https://github.com/cdfoundation/awards/blob/main/README.md
