### ISSUE TITLE
sigs on website

### ISSUE THREAD

**Issue by justinabrahms** [cdfoundation/foundation#383]
Hi cdfoundation folks.

Website question: Can we list the interoperability sigs there? It would be nice if folks going to cd.foundation could know those exist. It also feels a little odd to link to github for our landing site from a branding perspective.

**Comment by zestyroxy** [comment]
Hi @justinabrahms,

They are listed here: https://cd.foundation/community/ but you mean that their links should go to cd.foundation pages, not GitHub, correct? I believe the SIG content is on GitHub, because our site is WordPress hosted by the Linux Foundation, so the community can't edit it's content.

We could definitely link them from the cd.foundation main menu and give them a dedicated page.

@fdegir to add to our discussion list :)

**Comment by fdegir** [comment]
SIGs are listed on the website. Closing the issue.
