### ISSUE TITLE
Ensure CDF Awards Process is documented

### ISSUE THREAD

**Issue by fdegir** [cdfoundation/foundation#387]
CDF Awards is an important initiative within the CDF, recognising the individuals who make contributions to CDF  and its projects. Ensure the process of the CDF Awards is documented.

**Comment by uhafner** [comment]
In the Jenkins project elections typically are composed of the following steps:

1. Inform about the elections 
2. Let community members register for the votings
3. Perform the voting
4. Publish the voting results
    - Announce the results once they are available 
    - Make the results transparent by showing the exact votes for each candidate

I think for steps 1-3 everything was fine but step 4 needs improvements:
- I think you published the results at CDCon (which is fine) but you did not publish results on the same channels you asked for voters. So I would recommend that you write a mail with the results when the results have been announced at CDCon. Otherwise voters that were not at CDCon will be disappointed (like me).
- Most of us leave in free countries where election results are reported transparently. So it would make sense to publish the exact results as well. Otherwise the elections will have a bad smell (not sure how you call this in English). Without the results one might assume that you want to hide something (manipulations?).

**Comment by fdegir** [comment]
Thanks a lot for sharing the steps followed by the Jenkins Community.

> * So I would recommend that you write a mail with the results when the results have been announced at CDCon. Otherwise voters that were not at CDCon will be disappointed (like me).

We are working on a blog post to communicate the results and we will make sure to notify the community using various channels when the post is live. (e.g., social, slack)

> * Most of us live in free countries where election results are reported transparently.

This is exactly the reason why we started working on [identifying the missing processes/guidelines and documenting them](https://github.com/cdfoundation/foundation/labels/documentation), including but not limited to awards and elections.

Additionally, we would like the community members to join as election/awards officers and be part of the process from start to end, helping with the transparency further. 

The documents will be sent as PRs to this repository and community will be invited to review and provide feedback.

**Comment by fdegir** [comment]
Guidelines documented, closing the issue.

https://github.com/cdfoundation/foundation/blob/main/CDF%20Awards%20Guidelines.md
