### ISSUE TITLE
**The nomination period for The TOC Chair is open.** 

### ISSUE THREAD

**Issue by micmarti85** [cdfoundation/foundation#403]
**The nomination period for The TOC Chair is open.** 
Individuals interested in running for this position or individuals interested to nominate others must record the nominations under this GitHub issue. Please note that only [the current members of the TOC](https://github.com/cdfoundation/toc#members) are eligible to nominate themselves or be nominated by other members of the TOC. 

**Please include:**
Name of the candidate
Their biography and statement of intent on why they would be a good person to hold the position.
Any other relevant Information
 
If you are nominating someone other than yourself, please confirm their interest privately BEFORE you nominate them publicly. It is also required that individuals nominated by others accept their nominations directly under this GitHub issue.

**Responsibilities Include:**
Preside over meetings
Ensure minutes are taken
Drive the TOC agenda with input from the TOC representatives
Serve on the Governing Board as the TOC’s representative

Please see [Charter](https://github.com/cdfoundation/charter/blob/master/CHARTER.md#:~:text=)%20Officers,before%20the%20Governing%20Board.) for more information.

____________________________________________________________________________
**Election Cycle:**
July 19: Present election timeline to TOC 
July 20: Start of self-nomination period for the TOC Chair 
August 3, 11:45pm EST: End of self-nomination period for the TOC Chair 
August 4: Start of voting period 
August 15, 11:45pm EST: End of voting period and results announced 
August 16: The new chair gets seated during TOC Meeting 
Term: 8/16/2022 - 8/16/2023
____________________________________________________________________________

**Comment by oleg-nenashev** [comment]
After some consideration, I decided to put in my nomination for the second term

## Bio

Oleg is a TOC chair and community ambassador in the Continuous Delivery Foundation. Oleg is a core maintainer and board member in Jenkins, and also a Keptn maintainer. Open source software and open hardware advocate, active mentor and organizer for open source mentorships and outreach programs. Oleg has a PhD degree in hardware design and volunteers in the Free and Open Source Silicon Foundation. Oleg works on open source programs and Keptn community at the Dynatrace Open Source Program Office. 

## Statement

It has been an honor for me to serve as a CDF TOC Chair and governing board member. Should the TOC members vote for me, I am ready to continue for another term. My main priority would be to coordinate technical programs within the CDF, and to make all CDF operations as transparent as possible: roadmaps, open governance and accountability of elected roles. I plan to help member projects improve their community and governance processes so that they could improve and graduate in the CDF. Another priority will be interoperability between projects so that the CDF end users can easily combine them for their software delivery needs, especially facilitating open standards like CDEvents and their adoption in the CDF projects. Last but not least, my priority will be to onboard more TOC members and contributors, and to find candidates who would take the TOC Chair role in the next elections.

## Affiliations

* Employer: Dynatrace
* Projects: Jenkins, Keptn, OpenFeature, CDEvents, LibreCores
* Public roles in organizations: CNCF TOC Contributor, Free and Open Source Silicon Foundation (FOSSi), API Neuchatel
* Organization memberships: OSI, JUG.ch, CH Open
