### ISSUE TITLE
Create Tekton Conformance/Certification Program

### ISSUE THREAD

**Issue by caniszczyk** [cdfoundation/foundation#6]

**Comment by danlopez00** [comment]
ref: #2 

A security audit process is a building block to a full conformance program.

**Comment by fdegir** [comment]
The Tekton Community needs to have further conversations around this topic to describe what the actual conformance program would look like.

Here is the API Spec for reference: https://github.com/tektoncd/pipeline/blob/main/docs/api-spec.md

Closing this issue since it is pretty outdated. A new one will be created once the work is about to start.
