### ISSUE TITLE
define the narrative for CDF 

### ISSUE THREAD

**Issue by danlopez00** [cdfoundation/foundation#81]
define the narrative for CDF and for each of the projects as a blueprint on how to message CDF, projects especially for speakers in the speakers bureau

**Comment by jsalinas29** [comment]
- working this narrative as part of the event program plan

**Comment by timfong888** [comment]
Are you guys building up a messaging document based on this?  It'd be good to consolidate it.

**Comment by danlopez00** [comment]
Working with Cloud Foundry team and an outcome is to distill and consolidate for updates to messaging. This is in process

**Comment by jsalinas29** [comment]
Tracy Ragan is owning this project - fyi!  





On Mon, Apr 20, 2020 5:54 PM, Dan Lopez notifications@github.com  wrote:


Working with Cloud Foundry team and an outcome is to distill and consolidate for
updates to messaging. This is in process

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub, or unsubscribe.



Jacqueline SalinasContinuous Delivery FoundationDirector of Ecosystem & Co
mmunityjsalinas@contractor.linuxfoundation.orghttps://calendly.com/jsalinas-cdf
408 218 0667

**Comment by danlopez00** [comment]
This is complete for a v1.0 Draft
