### ISSUE TITLE
Follow up with Mentees that have applied on CommunityBridge

### ISSUE THREAD

**Issue by danlopez00** [cdfoundation/foundation#99]
https://people.communitybridge.org/project/515e26a1-9e56-49e6-bb87-ce5544e8ee10/mentees

Follow up with Mentees that have applied on CommunityBridge

**Comment by oleg-nenashev** [comment]
We also have mentees who applied to Jenkins. Unfortunately Communtiy Bridge does not offer a meaningful way to communicate with mentees unless they reach out to you using the documented channels

**Comment by jsalinas29** [comment]
Hi Dan - where do we access the applicants info?  





On Thu, Mar 5, 2020 5:22 PM, Dan Lopez notifications@github.com  wrote:
Assigned #99  to @jsalinas29.

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub, or unsubscribe.



Jacqueline SalinasContinuous Delivery FoundationDirector of Ecosystem & Co
mmunityjsalinas@contractor.linuxfoundation.orghttps://calendly.com/jsalinas-cdf
408 218 0667

**Comment by danlopez00** [comment]
we will need to coordinate with the CB product team outside of this ticket for looking at feature requests
